### ISSUE TITLE
1024x1024

### ISSUE THREAD

**Issue by naddika** [dnanhkhoa/rust-background-removal#4]
> The model resolution is limited to a maximum of 1024x1024 pixels.

Is this true for all the 3 onnx models in assets: small., medium, large? 

**ort-onnx** project doesn't mention this anywhere -- I haven't found it.

Is there any way to increase the resolution? To obtain a model with a bigger resoluation.

**Comment by dnanhkhoa** [comment]
> Is this true for all the 3 onnx models in assets: small., medium, large?
> **ort-onnx** project doesn't mention this anywhere -- I haven't found it.

Yes, the model architecture was designed to output a 1024x1024 image. It's based on the DIS model (https://github.com/xuebinqin/DIS), and you can refer to this line where 'd1' is upscaled to the size of 'x,' with 'x' being a 1024x1024 input image.
https://github.com/xuebinqin/DIS/blob/ec4a4f4f8d967f744bf857149d5ee343b59766b0/IS-Net/models/isnet.py#L591

> Is there any way to increase the resolution? To obtain a model with a bigger reoluation.

Honestly my knowledge in this area is very limited.
If you have substantial training data, you can train a new model with a higher dimension. Alternatively, you can explore the topic of Image Upscaling for more info.
